language: elixir
matrix:
  include:
    - elixir: 1.7.4
      otp_release: 21.3.8.1
    - elixir: 1.8.2
      otp_release: 21.3.8.1
    - elixir: 1.9.4
      otp_release: 21.3.8.1
    - elixir: 1.9.4
      otp_release: 22.0.7
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
