language: elixir
elixir:
  - 1.4.5
  - 1.5.1
otp_release:
  - 19.3
  - 20.0
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
